# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Volumes/cmake-3.4.1-Darwin-x86_64/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Volumes/cmake-3.4.1-Darwin-x86_64/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sookim/cse6140

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sookim/cse6140

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Volumes/cmake-3.4.1-Darwin-x86_64/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Volumes/cmake-3.4.1-Darwin-x86_64/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sookim/cse6140/CMakeFiles /Users/sookim/cse6140/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sookim/cse6140/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gitclean

# Build rule for target.
gitclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gitclean
.PHONY : gitclean

# fast build rule for target.
gitclean/fast:
	$(MAKE) -f CMakeFiles/gitclean.dir/build.make CMakeFiles/gitclean.dir/build
.PHONY : gitclean/fast

#=============================================================================
# Target rules for targets named runGA

# Build rule for target.
runGA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runGA
.PHONY : runGA

# fast build rule for target.
runGA/fast:
	$(MAKE) -f CMakeFiles/runGA.dir/build.make CMakeFiles/runGA.dir/build
.PHONY : runGA/fast

#=============================================================================
# Target rules for targets named sample

# Build rule for target.
sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample
.PHONY : sample

# fast build rule for target.
sample/fast:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/build
.PHONY : sample/fast

#=============================================================================
# Target rules for targets named CSE6140Utilities

# Build rule for target.
CSE6140Utilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CSE6140Utilities
.PHONY : CSE6140Utilities

# fast build rule for target.
CSE6140Utilities/fast:
	$(MAKE) -f src/CMakeFiles/CSE6140Utilities.dir/build.make src/CMakeFiles/CSE6140Utilities.dir/build
.PHONY : CSE6140Utilities/fast

runGA.o: runGA.cpp.o

.PHONY : runGA.o

# target to build an object file
runGA.cpp.o:
	$(MAKE) -f CMakeFiles/runGA.dir/build.make CMakeFiles/runGA.dir/runGA.cpp.o
.PHONY : runGA.cpp.o

runGA.i: runGA.cpp.i

.PHONY : runGA.i

# target to preprocess a source file
runGA.cpp.i:
	$(MAKE) -f CMakeFiles/runGA.dir/build.make CMakeFiles/runGA.dir/runGA.cpp.i
.PHONY : runGA.cpp.i

runGA.s: runGA.cpp.s

.PHONY : runGA.s

# target to generate assembly for a file
runGA.cpp.s:
	$(MAKE) -f CMakeFiles/runGA.dir/build.make CMakeFiles/runGA.dir/runGA.cpp.s
.PHONY : runGA.cpp.s

sample.o: sample.cpp.o

.PHONY : sample.o

# target to build an object file
sample.cpp.o:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/sample.cpp.o
.PHONY : sample.cpp.o

sample.i: sample.cpp.i

.PHONY : sample.i

# target to preprocess a source file
sample.cpp.i:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/sample.cpp.i
.PHONY : sample.cpp.i

sample.s: sample.cpp.s

.PHONY : sample.s

# target to generate assembly for a file
sample.cpp.s:
	$(MAKE) -f CMakeFiles/sample.dir/build.make CMakeFiles/sample.dir/sample.cpp.s
.PHONY : sample.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gitclean"
	@echo "... runGA"
	@echo "... sample"
	@echo "... CSE6140Utilities"
	@echo "... runGA.o"
	@echo "... runGA.i"
	@echo "... runGA.s"
	@echo "... sample.o"
	@echo "... sample.i"
	@echo "... sample.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

